channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.18.1
  - scikit-image=0.17.2
  - urllib3=1.25.9
  - json-c=0.13.1
  - requests=2.23.0
  - flask=1.1.2
  - shapely=1.7.0
  - pyproj=2.6.0
  - imantics=0.1.12
  - matplotlib=3.1.3
  - osmnx=0.12.1
  - pandas=1.0.3
  - folium=0.10.1
  - geojson=2.5.0
  - geojsonio=0.0.3
  - geopandas=0.7.0
  - imgaug=0.4.0
  - scipy=1.4.1
  - rasterio=1.1.3
  - pip=20.0.2
  - scikit-learn=0.22.1
  - pytz=2019.1
  - astropy=4.0.1
  - openpyxl=3.0.3
  - notebook
  - pip:
    - sentinelsat==0.13
    - image-slicer==0.3.0
    - earthengine-api==0.1.222
    - protobuf==3.12.0
    - tensorboard==1.15.0
    - tensorflow==1.15.2
    - keras==2.1.0
    - opencv-python==4.2.0.34